const { cmd } = require("../command");
const axios = require("axios");
const fs = require("fs");

cmd({
  pattern: "imagine",
  alias: ["flux"],
  react: "🚀",
  desc: "Generate an image using AI.",
  category: "ai",
  filename: __filename
}, async (conn, mek, m, { q, reply }) => {
  try {
    if (!q) return reply("Please provide a prompt for the image.");

    await reply("> *CREATING IMAGINE ...🔥*");

    const apiUrl = `https://api.siputzx.my.id/api/ai/flux?prompt=${encodeURIComponent(q)}`;

    const response = await axios.get(apiUrl, { responseType: "arraybuffer" });

    if (!response || !response.data) {
      return reply("Error: The API did not return a valid image. Try again later.");
    }

    const imageBuffer = Buffer.from(response.data, "binary");

    await conn.sendMessage(m.chat, {
      image: imageBuffer,
      caption: `💸 *Imagine Generated By KHAN MD* 🚀\n✨ Prompt: *${q}*`
    });

  } catch (error) {
    console.error("FluxAI Error:", error);
    reply(`An error occurred: ${error.response?.data?.message || error.message || "Unknown error"}`);
  }
});

cmd({
  pattern: "art",
  alias: ["magic", "imagine2"],
  desc: "Generate AI art using Magic Studio API",
  category: "ai",
  react: "🪄",
  filename: __filename
}, async (conn, mek, m, { from, q, reply }) => {
  try {
    if (!q) return await reply("🎨 Please provide a prompt!\n\nExample: *.art a man on the moon but sketch style*");

    await reply("*🪄 Creating your art, please wait*...");

    const apiUrl = `https://api.xyro.site/ai/magic-studio?prompt=${encodeURIComponent(q)}`;
    const response = await axios.get(apiUrl, { responseType: "arraybuffer" });

    const imageBuffer = Buffer.from(response.data, "binary");

    await conn.sendMessage(from, { image: imageBuffer, caption: `🎨 *AI Art Generated!*\n🧠 Prompt: ${q}\n\n✨ Powered By JawadTechX` }, { quoted: mek });

  } catch (e) {
    console.error(e);
    await reply("❌ Failed to generate art. Try again later.");
  }
});
